[2025-10-31T23:02:02.445+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:02:02.471+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:02:02.477+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:02:02.477+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T23:02:02.487+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam2> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:02:02.497+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:02:02.499+0700] {standard_task_runner.py:63} INFO - Started process 1947 to run task
[2025-10-31T23:02:02.507+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam2', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpl0_tkjsf']
[2025-10-31T23:02:02.515+0700] {standard_task_runner.py:91} INFO - Job 405: Subtask start_vehicle_producer_cam2
[2025-10-31T23:02:02.610+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:02:02.682+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:02:02.684+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:02:02.684+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:02:02.685+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam2.sh"']
[2025-10-31T23:02:02.697+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:02:02.708+0700] {subprocess.py:93} INFO - [Producer-CAM2] üèçÔ∏è Starting Vehicle Kafka Producer (Camera 2)...
[2025-10-31T23:02:02.732+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:02:02.732+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:02:02.733+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:02:02.733+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:02:02.736+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:02:02.737+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:02:02.746+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:02:02.750+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam2, execution_date=20251031T150000, start_date=20251031T160202, end_date=20251031T160202
[2025-10-31T23:02:02.756+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 405 for task start_vehicle_producer_cam2 (Bash command failed. The command returned a non-zero exit code 1.; 1947)
[2025-10-31T23:02:02.794+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:02:02.812+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:02:02.814+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-31T23:22:32.268+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:22:32.285+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:22:32.290+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:22:32.290+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T23:22:32.297+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam2> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:22:32.303+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2851) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:22:32.304+0700] {standard_task_runner.py:63} INFO - Started process 2864 to run task
[2025-10-31T23:22:32.306+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam2', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '462', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmp800qfq4z']
[2025-10-31T23:22:32.309+0700] {standard_task_runner.py:91} INFO - Job 462: Subtask start_vehicle_producer_cam2
[2025-10-31T23:22:32.355+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam2 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:22:32.418+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:22:32.419+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:22:32.420+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:22:32.420+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam2.sh"']
[2025-10-31T23:22:32.432+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:22:32.442+0700] {subprocess.py:93} INFO - [Producer-CAM2] üèçÔ∏è Starting Vehicle Kafka Producer (Camera 2)...
[2025-10-31T23:22:32.466+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:22:32.466+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:22:32.466+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:22:32.467+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:22:32.470+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:22:32.470+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:22:32.481+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:22:32.484+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam2, execution_date=20251031T150000, start_date=20251031T162232, end_date=20251031T162232
[2025-10-31T23:22:32.492+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 462 for task start_vehicle_producer_cam2 (Bash command failed. The command returned a non-zero exit code 1.; 2864)
[2025-10-31T23:22:32.519+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:22:32.536+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:22:32.536+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
