[2025-10-31T23:02:02.443+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:02:02.473+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:02:02.477+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:02:02.478+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T23:02:02.488+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam1> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:02:02.495+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1935) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:02:02.500+0700] {standard_task_runner.py:63} INFO - Started process 1945 to run task
[2025-10-31T23:02:02.499+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam1', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmp42k5pnwf']
[2025-10-31T23:02:02.506+0700] {standard_task_runner.py:91} INFO - Job 404: Subtask start_vehicle_producer_cam1
[2025-10-31T23:02:02.610+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:02:02.682+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:02:02.684+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:02:02.685+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:02:02.685+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam1.sh"']
[2025-10-31T23:02:02.698+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:02:02.708+0700] {subprocess.py:93} INFO - [Producer-CAM1] ðŸš— Starting Vehicle Kafka Producer (Camera 1)...
[2025-10-31T23:02:02.732+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:02:02.732+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:02:02.733+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:02:02.733+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:02:02.736+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:02:02.737+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:02:02.747+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:02:02.749+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam1, execution_date=20251031T150000, start_date=20251031T160202, end_date=20251031T160202
[2025-10-31T23:02:02.756+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 404 for task start_vehicle_producer_cam1 (Bash command failed. The command returned a non-zero exit code 1.; 1945)
[2025-10-31T23:02:02.795+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:02:02.822+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:02:02.823+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-31T23:22:32.237+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:22:32.251+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:22:32.255+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:22:32.255+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T23:22:32.262+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_vehicle_producer_cam1> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:22:32.268+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2849) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:22:32.269+0700] {standard_task_runner.py:63} INFO - Started process 2862 to run task
[2025-10-31T23:22:32.271+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'vehicle_pipeline_new_dag', 'start_vehicle_producer_cam1', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/vehicel_pipeline_new_dag.py', '--cfg-path', '/tmp/tmpj1mxvn9k']
[2025-10-31T23:22:32.273+0700] {standard_task_runner.py:91} INFO - Job 460: Subtask start_vehicle_producer_cam1
[2025-10-31T23:22:32.320+0700] {task_command.py:426} INFO - Running <TaskInstance: vehicle_pipeline_new_dag.start_vehicle_producer_cam1 scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:22:32.387+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vehicle_pipeline_new_dag' AIRFLOW_CTX_TASK_ID='start_vehicle_producer_cam1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:22:32.388+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:22:32.389+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:22:32.390+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/vehicle_count/scripts/run_producer_cam1.sh"']
[2025-10-31T23:22:32.400+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:22:32.410+0700] {subprocess.py:93} INFO - [Producer-CAM1] ðŸš— Starting Vehicle Kafka Producer (Camera 1)...
[2025-10-31T23:22:32.433+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:22:32.434+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/vehicle_count/scripts/vehicle_producer_single.py", line 13, in <module>
[2025-10-31T23:22:32.434+0700] {subprocess.py:93} INFO -     import cv2
[2025-10-31T23:22:32.434+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'cv2'
[2025-10-31T23:22:32.437+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:22:32.438+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:22:32.448+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:22:32.451+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=vehicle_pipeline_new_dag, task_id=start_vehicle_producer_cam1, execution_date=20251031T150000, start_date=20251031T162232, end_date=20251031T162232
[2025-10-31T23:22:32.464+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 460 for task start_vehicle_producer_cam1 (Bash command failed. The command returned a non-zero exit code 1.; 2862)
[2025-10-31T23:22:32.483+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:22:32.500+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:22:32.501+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
